#!/usr/bin/env python
"""
Authors: Carles Marin + Claude (AI assistant).

WHICH DISCRETE GROUP IS LEFT, AND WHAT WOULD DESTROY IT.

Section 6 of the paper says a vacuum expectation value of charge q_phi "breaks
U(1)' to a discrete subgroup" and never names it. Naming it is the first step of
the scalar sector Part VII needs, and it costs nothing: the bulk charge lattice
is exactly (1/2)Z (section 6), so the residual group is fixed by one ratio.

Three things, all group theory and none of them touching the potential:

  A. the residual Z_N for each q_phi their own representations supply
  B. which operator charges survive each, re-derived from the group and not from
     the A/q_phi rule -- two routes to the same table, so one can fail
  C. what a SECOND vacuum expectation value does, made explicit rather than
     quoted as a caveat: the residual is generated by gcd(q_1, q_2), and this
     lists exactly which pairs collapse the protection

None of this needs alpha_min, so none of it is hostage to the anchor discrepancy
of section 7. That is why it is the part of Part VII that can be done now.
"""
from fractions import Fraction as F
from itertools import combinations

P = lambda *a: print(*a, flush=True)

QUANTUM = F(1, 2)                    # the bulk lattice: extra(n) = (n_6 - n_7)/2
AVAIL = {F(1, 2): "7", F(1): "28", F(3, 2): "84"}   # pure index-7 components


def residual_N(q):
    """U(1)' -> Z_N. A charge lattice of quantum d broken by a VEV of charge q
    leaves the subgroup of phases trivial on the VEV: N = q/d when that is an
    integer."""
    r = q / QUANTUM
    return int(r) if r.denominator == 1 else None


P("=" * 78)
P("A -- THE RESIDUAL GROUP, NAMED")
P("=" * 78)
P("  bulk charge lattice: %s Z, quantum %s (section 6)" % (QUANTUM, QUANTUM))
P("")
P("  %-10s %-8s %-12s %s" % ("q_phi", "from", "residual", "meaning"))
for q, rep in sorted(AVAIL.items()):
    N = residual_N(q)
    note = ("Z_1 -- NOTHING survives: the VEV charge IS the quantum"
            if N == 1 else "Z_%d" % N)
    P("  %-10s %-8s %-12s %s" % (q, rep, "Z_%d" % N, note))
P("")
P("  >> q_phi = 3/2, the (777) of the 84, leaves Z_3.  That is the group the")
P("     mod-3 argument of section 6 is about, and the paper never names it.")
assert residual_N(F(3, 2)) == 3 and residual_N(F(1, 2)) == 1

P("")
P("=" * 78)
P("B -- WHAT SURVIVES Z_N, BY TWO ROUTES")
P("=" * 78)
P("  Route 1 (the paper): an operator of charge A can be dressed iff A/q_phi is")
P("  an integer.  Route 2 (the group): A must be trivial under the residual Z_N,")
P("  i.e. A/QUANTUM = 0 mod N.  If the two disagree anywhere, one is wrong.")
P("")
P("  %-8s %-9s %-11s %-11s %s" % ("q_phi", "A", "route 1", "route 2", "agree?"))
bad = 0
for q in sorted(AVAIL):
    N = residual_N(q)
    for m in range(-4, 5):
        A = F(3 * m + 1, 2)              # Green-Schwarz on: X_Q = m/2
        r1 = (A / q).denominator == 1
        r2 = (int(A / QUANTUM) % N == 0)
        if r1 != r2:
            bad += 1
        if m in (-1, 0, 1, 2):
            P("  %-8s %-9s %-11s %-11s %s"
              % (q, A, "dressable" if r1 else "forbidden",
                 "dressable" if r2 else "forbidden", "yes" if r1 == r2 else "*** NO ***"))
    P("")
P("  disagreements between the two routes, over all m in [-4,4] and all q_phi: %d" % bad)
assert bad == 0
P("  >> the selection rule IS the residual group, and not a separate assumption.")

P("")
P("=" * 78)
P("C -- WHAT A SECOND VACUUM EXPECTATION VALUE DESTROYS")
P("=" * 78)
P("  With two breaking scalars the residual group is generated by gcd(q1,q2),")
P("  so the protection is only as strong as the SMALLEST charge that condenses.")
P("  The paper states this and moves on. Here is the whole table, which is what")
P("  a scalar sector has to be built against.")
P("")
P("  %-18s %-10s %-12s %s" % ("pair", "gcd", "residual", "protection at GS charges"))


def protects(qeff):
    """does a residual of quantum qeff still forbid every A = (3m+1)/2?"""
    return all((F(3 * m + 1, 2) / qeff).denominator != 1 for m in range(-30, 31))


for a, b in combinations(sorted(AVAIL), 2):
    from math import gcd
    g = F(gcd(a.numerator * b.denominator, b.numerator * a.denominator),
          a.denominator * b.denominator)
    N = residual_N(g)
    P("  %-18s %-10s %-12s %s"
      % ("%s + %s" % (a, b), g, "Z_%s" % (N if N else "?"),
         "holds" if protects(g) else "DESTROYED"))
P("")
P("  single scalars, for comparison:")
for q in sorted(AVAIL):
    P("  %-18s %-10s %-12s %s"
      % ("%s alone" % q, q, "Z_%d" % residual_N(q),
         "holds" if protects(q) else "DESTROYED"))
P("")
P("  >> only q_phi = 3/2 ALONE protects.  Add the 7's scalar and gcd(3/2,1/2)")
P("     = 1/2 collapses the residual to Z_1; add the 28's and gcd(3/2,1) = 1/2")
P("     does the same.  So the scalar sector Part VII builds must give a VEV to")
P("     the 84's singlet and to NEITHER of the other two -- that is a condition")
P("     on the scalar potential, and it is the first thing that potential has to")
P("     be shown to do.")
P("")
P("  Note what this does NOT settle: why the potential prefers that direction.")
P("  Naming the group is group theory; making it dynamical is a potential, and")
P("  that is the next piece, not this one.")
